### PR TITLE
Added A Screenshot To README

### PR DESCRIPTION
**Pull request by azharakbar**

### CODE REVIEW

**Review by mjrdnk — CHANGES_REQUESTED** [review]
Thank you very much @azharakbar for your contribution to express-simple!
Could you remove browser tabs from the screen shot, to make it more generic?
Thanks!

**Comment by azharakbar** [comment]
@mjrdnk Sure .. :) Wil raise the new PR in few Minutes .. :)

**Comment by azharakbar** [comment]
@mjrdnk Did you mean to remove the Bookmarks ... or the Tabs ? Coz, i dont see any tabs in the screenshot ... :-/

**Review by mjrdnk — CHANGES_REQUESTED** [review]
Alright, please remove the <br> also, as it's not necessary for the markup. Thanks!

**Comment by mjrdnk** [comment]
Oh I meant the bookmarks! I am sorry!

**Comment by azharakbar** [comment]
@mjrdnk Sure .. :)

**Comment by azharakbar** [comment]
@mjrdnk Done .. :)

**Review by mjrdnk — APPROVED** [review]
Looks good. Thanks!

**Comment by azharakbar** [comment]
Thanks ... Pls merge it .. :) @mjrdnk

**Pull request merged**
